### ISSUE TITLE
Document src/js/_enqueues/admin/link.js

### ISSUE THREAD

**Issue by manuelaugustin** [Yoast/wordpress-develop-mirror#113]

**Comment by Dieterrr** [comment]
It seems in the meantime this file was documented by @atimmer, so I think we can be unassigned and depending on it's status this issue can be closed? 

I see now we made the mistake to forget to assign ourselves on WordPress.org, as the file still is unclaimed in the list: 
https://make.wordpress.org/core/2018/01/31/js-docs-initiative-add-inline-docs-for-javascript/
