### ISSUE TITLE
Update q-unit tests to reflect src-approach changes

### ISSUE THREAD

**Issue by danielFangstrom** [Yoast/wordpress-develop-mirror#95]
We need to fix the q-unit tests to reflect the src-approach changes.

In order to not forget for next week:

To do:

- [ ] index.html -> fix paths to files in src
- [ ] adjust structure in tests/qunit

**Comment by maartenleenders** [comment]
qunit should be `~/wordpress-develop-mirror/tests/js/integration/`, and all paths in `index.html` should point to build `../../build/[...]` instead of `../../src/[...]`

**Comment by maartenleenders** [comment]
For our info: 
...and branch should be branched off of a different branch than `prove/src-approach`, ask @omarreiss wich one exactly.

**Comment by omarreiss** [comment]
Fixed in https://github.com/Yoast/wordpress-develop-mirror/commit/1bb47b90a3493f184368f23b5f63bc47fdb73070
